# Generated by Django 3.2.12 on 2022-09-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.PositiveIntegerField(max_length=20)),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
    ]
